name: Security Framework Gates

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  packages: read
  id-token: write
  attestations: write

env:
  ENFORCEMENT: ${{ github.ref_name == github.event.repository.default_branch && 'block' || 'warn' }}

jobs:
  # --- Static & Dependency Analysis ---
  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python, actions
          build-mode: none
      - uses: github/codeql-action/analyze@v3

  dependency_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
        continue-on-error: ${{ env.ENFORCEMENT != 'block' }}

  # --- Build + SBOM + Attestation ---
  build_and_attest:
    needs: [ codeql, dependency_review ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build artifact
        run: |
          echo "hello $(date -u +%FT%TZ)" > artifact.txt
          sha256sum artifact.txt | tee checksums.txt

      - name: Export SBOM (GitHub API or Syft)
        id: sbom
        run: |
          set -euo pipefail
          gh api repos/${{ github.repository }}/dependency-graph/sbom -f ref=${{ github.sha }} \
            | jq '.sbom | fromjson' > sbom.spdx.json || \
          (curl -sSfL https://get.anchore.io/syft | sh -s -- -b /usr/local/bin && \
           syft dir:. -o spdx-json=sbom.spdx.json)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            artifact.txt
            checksums.txt
            sbom.spdx.json

      - name: Attest provenance
        if: github.event_name == 'push'
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: artifact.txt

      - name: Attest SBOM
        if: github.event_name == 'push'
        uses: actions/attest-sbom@v1
        with:
          subject-path: artifact.txt
          sbom-path: sbom.spdx.json

      - name: Verify attestations
        if: github.event_name == 'push'
        run: |
          set -euo pipefail
          WF_NOREF="${GITHUB_WORKFLOW_REF%@*}"
          for i in $(seq 1 6); do
            if gh attestation verify \
                  --repo "${{ github.repository }}" \
                  --subject-path artifact.txt \
                  --predicate-type "https://slsa.dev/provenance/v1" \
                  --signer-workflow "$WF_NOREF" \
                  --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
                  --deny-self-hosted-runners \
                  --limit 50 ; then
              echo "✓ Attestation verified"
              exit 0
            fi
            sleep 10
          done
          if [ "${ENFORCEMENT}" = "block" ]; then
            exit 1
          else
            echo "::warning::Attestation verification failed"
          fi

  # --- Secrets / Repo Security Flags ---
  security_settings_guard:
    runs-on: ubuntu-latest
    steps:
      - run: |
          DATA=$(gh api repos/${{ github.repository }})
          SEC=$(echo "$DATA" | jq -r '.security_and_analysis')
          SS=$(echo "$SEC" | jq -r '.secret_scanning.status')
          PP=$(echo "$SEC" | jq -r '.secret_scanning_push_protection.status')
          echo "Secret scanning: $SS, Push protection: $PP"
          if [ "$SS" != "enabled" ] || [ "$PP" != "enabled" ]; then
            if [ "${ENFORCEMENT}" = "block" ]; then
              exit 1
            else
              echo "::warning::Enable Secret scanning + Push protection"
            fi
          fi

  # --- Promote to Production ---
  promote_to_prod:
    needs: [ build_and_attest, security_settings_guard ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: production
    concurrency:
      group: deploy-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - run: |
          echo "All upstream gates passed. Waiting for env approval…"
