name: Incident Intake (alerts → tickets)

on:
  workflow_run:
    workflows: ["Security Framework Gates"]
    types: [completed]
  repository_vulnerability_alert:
    types: [create]

permissions:
  contents: read
  issues: write

jobs:
  open_incident_issue:
    if: >
      (github.event_name == 'workflow_run' &&
       (github.event.workflow_run.conclusion == 'failure' ||
        github.event.workflow_run.conclusion == 'timed_out')) ||
      (github.event_name == 'repository_vulnerability_alert')
    runs-on: ubuntu-latest
    steps:
      - name: Create incident issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          TMP="$(mktemp)"

          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            TITLE="INC: Security Framework Gates failed in ${GITHUB_REPOSITORY}"
            {
              echo "# Auto-created incident"
              echo
              echo "**Workflow:** Security Framework Gates"
              echo "**Run:** ${{ github.event.workflow_run.html_url }}"
              echo "**Branch:** ${{ github.event.workflow_run.head_branch }}"
              echo
              echo "@MainMuck/oncall"
            } > "$TMP"
            LABELS="incident,P1"
          else
            TITLE="INC: New Dependabot alert in ${GITHUB_REPOSITORY}"
            {
              echo "# Auto-created incident (Dependabot)"
              echo
              echo "See: https://github.com/${GITHUB_REPOSITORY}/security/dependabot"
              echo
              echo "@MainMuck/oncall"
            } > "$TMP"
            LABELS="incident,P2"
          fi

          gh issue create --title "$TITLE" --body-file "$TMP" --label "$LABELS"
