name: Quarterly Restore Test

on:
  schedule:
    - cron: '23 3 1 1,4,7,10 *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  restore-test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download latest backup & check
        env:
          B: ${{ vars.BACKUP_BUCKET }}
        run: |
          set -euo pipefail
          test -n "$B"

          key=$(aws s3 ls "s3://$B/backups/" --recursive | sort | awk '{print $4}' | tail -n1)
          if [ -z "$key" ]; then
            echo "::notice::No backups found in s3://$B/backups — skipping restore test"
            exit 0
          fi

          echo "Downloading s3://$B/$key"
          aws s3 cp "s3://$B/$key" backup.tgz

          echo "::group::Archive preview"
          tar tzf backup.tgz | head -n 50
          echo "::endgroup::"

          mkdir -p restore
          tar xzf backup.tgz -C restore

          # новый/старый формат раскладки
          test -d restore/workflows || test -d restore/.github/workflows || {
            echo "::error::No workflows dir in archive"
            ls -la restore || true
            exit 1
          }

          # при желании можно проверить и trust
          if [ -d restore/trust ] || [ -d restore/.github/trust ]; then
            echo "✓ trust dir present"
          fi

          echo "OK"
