name: Quarterly Restore Test

on:
  schedule:
    - cron: '23 3 1 1,4,7,10 *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  restore-test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download latest backup & check
        env:
          B: ${{ vars.BACKUP_BUCKET }}
        run: |
          set -euo pipefail
          test -n "$B"

          key=$(aws s3 ls "s3://$B/backups/" --recursive | sort | awk '{print $4}' | tail -n1)
          if [ -z "$key" ]; then
            echo "::notice::No backups found in s3://$B/backups — skipping restore test"
            exit 0
          fi

          echo "Downloading s3://$B/$key"
          aws s3 cp "s3://$B/$key" backup.tgz

          echo "::group::Archive preview"
          tar tzf backup.tgz | head -n 50
          echo "::endgroup::"

          mkdir -p restore
          tar xzf backup.tgz -C restore

          # принимаем и новый формат (workflows/trust), и старый (.github/workflows/.github/trust)
          if [ -d restore/workflows ]; then
            echo "✓ Found 'restore/workflows'"
          elif [ -d restore/.github/workflows ]; then
            echo "✓ Found legacy 'restore/.github/workflows'"
          else
            echo "::error::Neither 'restore/workflows' nor 'restore/.github/workflows' exists"
            ls -la restore || true
            exit 1
          fi

          if [ -d restore/trust ]; then
            echo "✓ Found 'restore/trust'"
          elif [ -d restore/.github/trust ]; then
            echo "✓ Found legacy 'restore/.github/trust'"
          else
            echo "::error::Neither 'restore/trust' nor 'restore/.github/trust' exists"
            ls -la restore || true
            exit 1
          fi

          echo "OK"
